"""empty message

Revision ID: aeaf199349ec
Revises: 
Create Date: 2019-12-27 00:00:01.725025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaf199349ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haberler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('haberKodu', sa.String(length=30), nullable=True),
    sa.Column('haberTuru', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('haberler')
    # ### end Alembic commands ###
