"""empty message

Revision ID: edd3c7be735d
Revises: aeaf199349ec
Create Date: 2019-12-27 00:24:40.029617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd3c7be735d'
down_revision = 'aeaf199349ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haberler', sa.Column('haberIcerik', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('haberler', 'haberIcerik')
    # ### end Alembic commands ###
